apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-auth-service-app
  labels:
    app: iam-auth-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-auth-service-app
  template:
    metadata:
      labels:
        app: iam-auth-service-app
    spec:
      containers:
        - name: iam-auth-service-app
          image: 30011989/iam-auth-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: iam-auth-service-svc
spec:
  type: LoadBalancer
  ports:
    - targetPort: 9100
      port: 80
  selector:
    app: iam-auth-service-app